version: '2.1'

services:

  postgis:
    image: postgis/postgis:latest
    volumes:
      - 'postgis-data:/usr/share/postgresql/data'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=GoDb

volumes:
  postgis-data: